const Tool = require('../core/Tool');

/**
 * 중복 콘텐츠 체크 도구 (네이버 저품질 방지)
 *
 * - 내부 중복: 본문 내 반복 문장/문단 검출
 * - 외부 중복: 흔한 복붙 패턴 탐지
 * - 네이버 D.I.A. 원본성 평가 시뮬레이션
 * - 자동 생성 콘텐츠 패턴 탐지
 * - 저품질 위험도 종합 평가
 */
class DuplicateCheckerTool extends Tool {
  constructor() {
    super({
      name: 'duplicate_checker',
      description: '중복 콘텐츠를 검출하고 네이버 저품질 위험도를 평가합니다.',
      parameters: {
        content: { type: 'string', description: '검사할 본문 텍스트' },
        keyword: { type: 'string', description: '메인 키워드' },
      },
    });
  }

  async execute({ content, keyword = '' }) {
    if (!content) throw new Error('검사할 본문(content)은 필수입니다.');

    // 1. 내부 중복 검사 (같은 글 내 반복)
    const internalDupes = this._checkInternalDuplication(content);

    // 2. 복붙/템플릿 패턴 탐지
    const templatePatterns = this._detectTemplatePatterns(content);

    // 3. 키워드 스터핑 검사
    const keywordStuffing = this._checkKeywordStuffing(content, keyword);

    // 4. 자동 생성 콘텐츠 패턴 검사
    const autoGenPatterns = this._detectAutoGenerated(content);

    // 5. 네이버 D.I.A. 원본성 시뮬레이션
    const originalityScore = this._simulateOriginality(content, internalDupes, templatePatterns, keywordStuffing, autoGenPatterns);

    // 6. 저품질 위험도 종합 평가
    const riskAssessment = this._assessRisk(originalityScore, internalDupes, templatePatterns, keywordStuffing, autoGenPatterns);

    return {
      originalityScore,
      riskAssessment,
      internalDupes,
      templatePatterns,
      keywordStuffing,
      autoGenPatterns,
      checkedAt: new Date().toISOString(),
    };
  }

  _checkInternalDuplication(content) {
    const sentences = content.split(/[.!?]\s/).filter(s => s.trim().length > 10);
    const duplicates = [];
    const seen = new Map();

    sentences.forEach((sentence, i) => {
      // 정규화: 공백/특수문자 제거 후 비교
      const normalized = sentence.replace(/\s+/g, '').replace(/[^가-힣a-zA-Z0-9]/g, '').toLowerCase();

      if (normalized.length < 10) return;

      if (seen.has(normalized)) {
        duplicates.push({
          type: 'exact',
          sentence: sentence.trim().substring(0, 60) + '...',
          firstOccurrence: seen.get(normalized) + 1,
          duplicateAt: i + 1,
        });
      } else {
        seen.set(normalized, i);
      }

      // 유사 문장 체크 (앞 20자가 같은 경우)
      const prefix = normalized.substring(0, 20);
      const prefixKey = `prefix_${prefix}`;
      if (seen.has(prefixKey) && !seen.has(normalized)) {
        duplicates.push({
          type: 'similar',
          sentence: sentence.trim().substring(0, 60) + '...',
          firstOccurrence: seen.get(prefixKey) + 1,
          duplicateAt: i + 1,
        });
      } else if (!seen.has(prefixKey)) {
        seen.set(prefixKey, i);
      }
    });

    return {
      found: duplicates.length,
      duplicates,
      status: duplicates.length === 0 ? 'pass' : duplicates.length <= 2 ? 'warning' : 'fail',
      message: duplicates.length === 0
        ? '내부 중복이 없습니다.'
        : `${duplicates.length}개 중복/유사 문장이 발견되었습니다.`,
    };
  }

  _detectTemplatePatterns(content) {
    const patterns = [];

    // 흔한 복붙 템플릿 패턴
    const templateSignals = [
      { pattern: /이 포스팅은.*활동의 일환/g, name: '어필리에이트 고지', risk: 'none', note: '필수 문구 (정상)' },
      { pattern: /본 포스팅은.*체험단.*제공/g, name: '체험단 고지', risk: 'low', note: '체험단 글로 인식됨' },
      { pattern: /출처\s*[:：]?\s*[가-힣]+/g, name: '출처 표기', risk: 'none', note: '출처 표기 (정상)' },
      { pattern: /^안녕하세요.*블로그입니다/m, name: '정형화 인사', risk: 'low', note: '매 글마다 같은 인사는 피하세요' },
      { pattern: /(\*\*[^*]{3,15}\*\*\n\n){4,}/g, name: '반복 구조', risk: 'medium', note: '같은 형식의 소제목이 연속으로 반복됩니다' },
      { pattern: /(장점|단점|특징)\s*\n(-\s*.+\n){6,}/g, name: '나열형 반복', risk: 'low', note: '리스트가 너무 길면 요약을 추가하세요' },
    ];

    templateSignals.forEach(({ pattern, name, risk, note }) => {
      const matches = content.match(pattern);
      if (matches && risk !== 'none') {
        patterns.push({
          name,
          risk,
          count: matches.length,
          note,
          preview: matches[0].substring(0, 50),
        });
      }
    });

    return {
      found: patterns.length,
      patterns,
      status: patterns.filter(p => p.risk === 'medium' || p.risk === 'high').length === 0 ? 'pass' : 'warning',
    };
  }

  _checkKeywordStuffing(content, keyword) {
    if (!keyword) return { status: 'skip', message: '키워드가 제공되지 않았습니다.' };

    const charCount = content.replace(/\s/g, '').length;
    const keywordCount = (content.match(new RegExp(keyword, 'g')) || []).length;
    const keywordChars = keyword.replace(/\s/g, '').length * keywordCount;
    const density = Math.round((keywordChars / charCount) * 1000) / 10;

    // 연속 키워드 패턴 체크
    const consecutivePattern = new RegExp(`(${keyword}[\\s,]*){2,}`, 'g');
    const consecutiveMatches = content.match(consecutivePattern) || [];

    // 태그 영역 키워드 과다 체크
    const tagArea = content.match(/#[^\s#]+/g) || [];
    const keywordTags = tagArea.filter(t => t.includes(keyword.replace(/\s+/g, '')));

    const issues = [];

    if (density > 5) {
      issues.push({
        type: '키워드 밀도 과다',
        severity: 'high',
        detail: `키워드 밀도 ${density}% (권장: 2~3%)`,
        action: `"${keyword}" 사용을 ${Math.ceil(keywordCount * 0.5)}회로 줄이세요.`,
      });
    } else if (density > 3.5) {
      issues.push({
        type: '키워드 밀도 주의',
        severity: 'medium',
        detail: `키워드 밀도 ${density}% (권장: 2~3%)`,
        action: '약간 높습니다. 동의어나 대체 표현을 활용하세요.',
      });
    }

    if (consecutiveMatches.length > 0) {
      issues.push({
        type: '연속 키워드',
        severity: 'high',
        detail: `"${keyword}"가 연속으로 반복됩니다.`,
        found: consecutiveMatches.map(m => m.substring(0, 40)),
        action: '네이버가 스팸으로 판정합니다. 자연스럽게 분산 배치하세요.',
      });
    }

    if (keywordTags.length > 5) {
      issues.push({
        type: '태그 내 키워드 과다',
        severity: 'medium',
        detail: `태그 ${keywordTags.length}개에 "${keyword}" 포함`,
        action: '태그에 같은 키워드 변형을 과다 사용하면 스팸 판정됩니다.',
      });
    }

    return {
      keyword,
      count: keywordCount,
      density: `${density}%`,
      consecutiveCount: consecutiveMatches.length,
      issues,
      status: issues.some(i => i.severity === 'high') ? 'fail' :
              issues.length > 0 ? 'warning' : 'pass',
    };
  }

  _detectAutoGenerated(content) {
    const signals = [];

    // 자연스럽지 않은 패턴 탐지
    const checks = [
      {
        name: '과도한 구조화',
        test: () => {
          const boldCount = (content.match(/\*\*[^*]+\*\*/g) || []).length;
          const lineCount = content.split('\n').filter(l => l.trim()).length;
          return boldCount / lineCount > 0.5;
        },
        message: '볼드 텍스트 비율이 너무 높습니다. 자연스러운 문체로 수정하세요.',
      },
      {
        name: '이모지 과다',
        test: () => {
          const emojis = content.match(/[\u{1F600}-\u{1F64F}\u{1F300}-\u{1F5FF}\u{2600}-\u{26FF}⭐📌🔍💡💰🛒📋📊✅❌👉🎯]/gu) || [];
          return emojis.length > content.length / 100;
        },
        message: '이모지 사용이 과도합니다. 핵심 포인트에만 사용하세요.',
      },
      {
        name: '정보 없는 공문구',
        test: () => {
          const fluff = (content.match(/정말\s*좋|너무\s*좋|완전\s*좋|진짜\s*좋|매우\s*좋/g) || []).length;
          return fluff > 5;
        },
        message: '"정말 좋다" 류의 공허한 표현이 많습니다. 구체적 장점을 서술하세요.',
      },
      {
        name: '동일 구조 반복',
        test: () => {
          const paragraphs = content.split('\n\n').filter(p => p.trim().length > 30);
          if (paragraphs.length < 3) return false;
          const structures = paragraphs.map(p => {
            const lines = p.split('\n').length;
            const hasBold = /\*\*/.test(p);
            const hasList = /^[-*•]/.test(p);
            return `${lines}-${hasBold}-${hasList}`;
          });
          const uniqueStructures = new Set(structures);
          return uniqueStructures.size < structures.length * 0.4;
        },
        message: '문단 구조가 너무 획일적입니다. 다양한 형식을 섞으면 자연스럽습니다.',
      },
    ];

    checks.forEach(({ name, test, message }) => {
      if (test()) {
        signals.push({ name, message });
      }
    });

    return {
      found: signals.length,
      signals,
      status: signals.length === 0 ? 'pass' : signals.length <= 1 ? 'warning' : 'fail',
      message: signals.length === 0
        ? '자동 생성 패턴이 감지되지 않았습니다.'
        : `${signals.length}개 자동 생성 의심 패턴이 발견되었습니다.`,
    };
  }

  _simulateOriginality(content, internal, template, keyword, autoGen) {
    let score = 100;

    // 내부 중복 감점
    score -= internal.found * 5;

    // 템플릿 패턴 감점
    template.patterns.forEach(p => {
      if (p.risk === 'high') score -= 15;
      else if (p.risk === 'medium') score -= 8;
      else if (p.risk === 'low') score -= 3;
    });

    // 키워드 스터핑 감점
    if (keyword.status === 'fail') score -= 20;
    else if (keyword.status === 'warning') score -= 8;

    // 자동 생성 감점
    score -= autoGen.found * 7;

    // 글 길이 보너스
    const charCount = content.replace(/\s/g, '').length;
    if (charCount >= 2000) score = Math.min(100, score + 5);
    if (charCount >= 3000) score = Math.min(100, score + 3);

    return {
      score: Math.max(0, Math.min(100, Math.round(score))),
      grade: score >= 85 ? 'A' : score >= 70 ? 'B' : score >= 55 ? 'C' : 'D',
      naverRisk: score >= 80 ? '안전' : score >= 60 ? '주의' : '위험',
    };
  }

  _assessRisk(originality, internal, template, keyword, autoGen) {
    const risks = [];

    if (originality.score < 60) {
      risks.push({
        level: 'critical',
        area: '원본성',
        message: `원본성 점수 ${originality.score}점. 네이버 저품질 판정 위험이 높습니다.`,
        action: '글 전체를 본인만의 문체로 재작성하세요.',
      });
    }

    if (internal.status === 'fail') {
      risks.push({
        level: 'high',
        area: '내부 중복',
        message: `${internal.found}개 중복 문장. 같은 표현 반복은 저품질 신호입니다.`,
        action: '중복 문장을 삭제하거나 다른 표현으로 바꾸세요.',
      });
    }

    if (keyword.status === 'fail') {
      risks.push({
        level: 'high',
        area: '키워드 스터핑',
        message: `키워드 밀도 ${keyword.density}. 스팸 판정 위험.`,
        action: '키워드 사용을 줄이고 동의어/대체 표현을 사용하세요.',
      });
    }

    if (autoGen.status === 'fail') {
      risks.push({
        level: 'medium',
        area: '자동 생성 패턴',
        message: '기계적으로 생성된 글처럼 보이는 패턴이 있습니다.',
        action: '개인적 경험, 의견, 감상을 추가하세요.',
      });
    }

    const overallLevel = risks.some(r => r.level === 'critical') ? 'critical' :
                          risks.some(r => r.level === 'high') ? 'high' :
                          risks.length > 0 ? 'medium' : 'low';

    return {
      level: overallLevel,
      label: overallLevel === 'critical' ? '매우 위험' :
             overallLevel === 'high' ? '위험' :
             overallLevel === 'medium' ? '주의' : '안전',
      risks,
      publishable: overallLevel !== 'critical' && overallLevel !== 'high',
      recommendation: overallLevel === 'low'
        ? '발행해도 좋습니다. 원본성이 확보되어 있습니다.'
        : '아래 위험 요소를 수정한 후 발행하세요.',
    };
  }
}

module.exports = DuplicateCheckerTool;
